"""把标注导出为 YOLO（Ultralytics）数据集 zip。

结构：
    <name>/
        data.yaml
        classes.txt
        images/train/*.png   images/val/*.png
        labels/train/*.txt   labels/val/*.txt
标签行：class_id xc yc w h   （均按图片宽高归一化到 0~1）
"""
from __future__ import annotations

import io
import zipfile

from app.schemas import ExportRequest
from app.services.store import store


def _label_lines(annos, width: int, height: int, n_classes: int) -> list[str]:
    lines: list[str] = []
    for a in annos:
        cid = int(a.class_id)
        if not (0 <= cid < n_classes):
            continue  # 越界类别会让 Ultralytics 训练时报错，直接跳过
        x1, x2 = sorted((a.x1, a.x2))
        y1, y2 = sorted((a.y1, a.y2))
        # 裁剪到图像范围
        x1 = min(max(x1, 0.0), width)
        x2 = min(max(x2, 0.0), width)
        y1 = min(max(y1, 0.0), height)
        y2 = min(max(y2, 0.0), height)
        bw = x2 - x1
        bh = y2 - y1
        if bw <= 1e-6 or bh <= 1e-6 or width <= 0 or height <= 0:
            continue
        xc = (x1 + x2) / 2.0 / width
        yc = (y1 + y2) / 2.0 / height
        nw = bw / width
        nh = bh / height
        lines.append(f"{cid} {xc:.6f} {yc:.6f} {nw:.6f} {nh:.6f}")
    return lines


def _names_yaml(classes: list[str]) -> str:
    items = ", ".join(_yaml_str(c) for c in classes)
    return f"[{items}]"


def _yaml_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _split_assignment(image_ids: list[str], train_ratio: float | None) -> dict[str, str]:
    """确定性切分：按 image_id 排序，后 n_val 个进 val。"""
    if train_ratio is None or train_ratio >= 1.0:
        return {iid: "train" for iid in image_ids}
    ratio = max(0.0, min(1.0, train_ratio))
    ordered = sorted(image_ids)
    n = len(ordered)
    n_val = max(0, min(n, round(n * (1.0 - ratio))))
    # 图片很少时 round 可能为 0，但用户既然选了划分，至少留 1 张验证（n>=2 时）
    if n_val == 0 and n >= 2:
        n_val = 1
    val_set = set(ordered[n - n_val:]) if n_val else set()
    return {iid: ("val" if iid in val_set else "train") for iid in ordered}


def build_yolo_zip(req: ExportRequest) -> tuple[bytes, str]:
    image_ids = [it.image_id for it in req.items]
    assignment = _split_assignment(image_ids, req.train_ratio)
    has_val = any(v == "val" for v in assignment.values())

    used_names: set[str] = set()
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for idx, item in enumerate(req.items):
            stored = store.get(item.image_id)
            if stored is None:
                continue
            split = assignment.get(item.image_id, "train")

            # 唯一文件名（stem 可能重复）
            stem = stored.filename.rsplit(".", 1)[0]
            name = stem
            k = 0
            while name in used_names:
                k += 1
                name = f"{stem}_{k}"
            used_names.add(name)

            img_bytes = store.get_bytes(item.image_id)
            z.writestr(f"images/{split}/{name}.png", img_bytes)

            lines = _label_lines(item.annotations, stored.width, stored.height, len(req.classes))
            z.writestr(f"labels/{split}/{name}.txt", "\n".join(lines) + ("\n" if lines else ""))

        # classes.txt
        z.writestr("classes.txt", "\n".join(req.classes) + ("\n" if req.classes else ""))

        # data.yaml
        val_line = "val: images/val\n" if has_val else "val: images/train\n"
        data_yaml = (
            "# YOLO dataset generated by labeling-auto\n"
            "path: .\n"
            "train: images/train\n"
            f"{val_line}"
            f"nc: {len(req.classes)}\n"
            f"names: {_names_yaml(req.classes)}\n"
        )
        z.writestr("data.yaml", data_yaml)

    return buf.getvalue(), f"{req.dataset_name or 'dataset'}.zip"
